### ISSUE TITLE
rds css specificity is often an issue because of lazy loading

### ISSUE THREAD

**Issue by tolu** [lfbergee/rtv-ds#278]
Because we do code splitting (on strim.no), which must be considered a standard these days, sometimes pulling in rds-CSS in new chunk overrides previously loaded CSS.

The issue is styling on a single class where CSS-order effectively wins all the time.

Potential solutions
- style on something with less specificity (`:is(.className)`?) (check browser support)
- figure out better way to only ever include rds-CSS once in consumer apps!

**Comment by lfbergee** [comment]
Agreed. It is a client issue, but the lib only exist to support clients so we should do something. 

My suggestion:
1. Supply all styles in a single css file that the clients can preload. Its about 35kb now, so not super duper awesome, but not that bad either. It will grow, so we should revisit if it becomes a problem. 
2. Keep supplying scss files individually, so clients can keep building optimized builds if other build systems is more clever to treeshake out multiple imports of same file.

**Comment by lfbergee** [comment]
Applied in 0.7.0 release
