### ISSUE TITLE
Fix da buttons

### ISSUE THREAD

**Issue by tolu** [lfbergee/rtv-ds#89]
Efter lite real life usage med knapper

- `forwardRef` på knapper
- `align-self: center` på icons
- använd solida färger som knapp-bakgrund

![image](https://user-images.githubusercontent.com/658586/131511221-e65bf7dd-58ba-46ea-87f4-02d05eaf2167.png)

[#FAED6F, #FCF4A9, #FAED6F, #B2BFBF]

![image](https://user-images.githubusercontent.com/658586/131511314-1890f09a-eecb-4c25-9e21-475c8bdf34f1.png)

[#002A2A, #FFFFFF, #001D1D, #B2BFBF]

![image](https://user-images.githubusercontent.com/658586/131511354-c323d547-1262-4f1d-8401-a8790ae7013b.png)

[#193F3F, #004B50, #001515, #B2BFBF]

**Comment by Smolandian** [comment]
I fixed da buttons!
